# Generated by Django 3.1.7 on 2021-06-08 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=15)),
                ('nascimento', models.DateField()),
                ('nome_pai', models.CharField(max_length=50)),
                ('nome_mae', models.CharField(max_length=50)),
                ('nacionalidade', models.CharField(max_length=10)),
                ('naturalidade', models.CharField(max_length=15)),
                ('estado_civil', models.CharField(max_length=10)),
                ('escolaridade', models.CharField(max_length=15)),
                ('cidade', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=20)),
                ('num_casa', models.IntegerField()),
                ('endereco', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=15)),
                ('profissao', models.CharField(max_length=15)),
                ('categoria', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pessoa')),
            ],
        ),
    ]
