# Generated by Django 3.1.7 on 2021-06-10 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='escolaridade',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='nacionalidade',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='nascimento',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='naturalidade',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='nome_mae',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='nome_pai',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='num_casa',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='profissao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='telefone',
        ),
    ]
